version: "3.8"
services:
  central_base_station:
    build:
      context: .
      dockerfile: Dockerfile.central_base_station
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=kafka:9092
    networks:
      - my_bridge_network

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - my_bridge_network

  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - my_bridge_network

  # elastic:
  #   image: "docker.elastic.co/elasticsearch/elasticsearch:7.13.2"
  #   environment:
  #     - node.name=elastic
  #     - cluster.name=docker-cluster
  #     - discovery.seed_hosts=elastic
  #     - cluster.initial_master_nodes=elastic
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - my_bridge_network

  # kibana:
  #   image: "docker.elastic.co/kibana/kibana:7.13.2"
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elastic:9200
  #   networks:
  #     - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge
