---
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
    - name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
      ports:
        - containerPort: 9200
        - containerPort: 9300
      env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
    - name: kibana
      image: docker.elastic.co/kibana/kibana:8.7.0
      ports:
        - containerPort: 5601
      env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - name: elasticsearch-host
      port: 9200
      targetPort: 9200
      nodePort: 30001
    - name: kibana
      port: 5601
      targetPort: 5601
      nodePort: 30002

