---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
spec:
  containers:
    - name: kafka
      image: bitnami/kafka:latest
      ports:
        - containerPort: 9092
      env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://localhost:9092"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
    - name: zookeeper
      image: bitnami/zookeeper:latest
      ports:
        - containerPort: 2181
      env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
