---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data-2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lsm-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parquet-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany # Elastic search also want to read this volume
  resources:
    requests:
      storage: 2Gi