---
apiVersion: v1
kind: Pod
metadata:
  name: test2
  labels: 
    app: test2
spec:
  containers:
    - name: test2
      image: nginxdemos/hello
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test2
spec:
  selector:
    app: test2
  ports:
    - port: 8002
      targetPort: 80
