---
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:
  volumes:
    - name: parquet-data
      persistentVolumeClaim:
        claimName: parquet-pv-claim
  containers:
    - name: test
      image: eclipse-temurin:11
      volumeMounts:
        - mountPath: "/parquet-data"
          name: parquet-data

